# vi: ft=python
import platform

env = Environment()

sources = ["demo.cpp"]
libs = ["SDL2", "SDL2_gfx"]



if platform.system() == "Darwin":
    # MacOS
    includes = [
        "/opt/homebrew/Cellar/sdl2/2.28.4/include/",
        "/opt/homebrew/Cellar/sdl2_gfx/1.0.4/include/",
    ]
    lib_path = ["/opt/homebrew/lib"]
else:
    includes = []
    lib_path = []

python3_builder = Builder(action="python3 $SOURCE > $TARGET")
env.Append(BUILDERS={"Python3": python3_builder})
env.Python3("../offsets.hpp", "../offsets.py")

demo = env.Program(
    target="demo",
    source=sources,
    CPPPATH=includes,
    LIBPATH=lib_path,
)
env.Append(LIBS=libs)
env.Append(CCFLAGS="-DDEMO -std=c++11 -g -Wall -Wextra -Weffc++")

Default(demo)
