# vi: ft=python

env = Environment()

sources = ["demo.cpp"]
libs = ["SDL2", "SDL2_gfx", "SDL2_image"]

demo = env.Program(target="demo", source=sources)
env.Append(LIBS=libs)
env.Append(CCFLAGS="-DDEMO")

Default(demo)
